// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// Problem RFC 9457 Problem Details. Served as `application/problem+json`.
//
// `type` is the machine-readable identity of the failure and is what a
// client should branch on — HTTP status alone is too coarse, since one
// 409 can mean several different things. `title` is for humans and may be
// reworded without notice, so clients must not match on it.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	//
	// Example: No workout with id 01H8X... exists for this user.
	Detail *string `json:"detail,omitempty"`

	// Instance URI identifying this specific occurrence.
	//
	// Example: /workouts/01H8X...
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code, repeated here for logs and clients that lose it.
	//
	// Example: 404
	Status int32 `json:"status"`

	// Title Short human-readable summary. Do not branch on this.
	//
	// Example: Workout not found
	Title string `json:"title"`

	// Type Stable URI identifying the problem type. Treat it as an identifier, not a link; it need not resolve.
	//
	//
	// Example: https://errors.example.com/workout-not-found
	Type string `json:"type"`
}

// Version defines model for Version.
type Version struct {
	// Version Semantic version of the running build
	//
	// Example: 0.0.0
	Version string `json:"version"`
}

// InternalServerError RFC 9457 Problem Details. Served as `application/problem+json`.
//
// `type` is the machine-readable identity of the failure and is what a
// client should branch on — HTTP status alone is too coarse, since one
// 409 can mean several different things. `title` is for humans and may be
// reworded without notice, so clients must not match on it.
type InternalServerError = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetVersion Report the version the running service was built from
	// (GET /version)
	GetVersion(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
}

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersion500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetVersion500ApplicationProblemPlusJSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetVersion Report the version the running service was built from
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(ctx *gin.Context) {
	var request GetVersionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"lFbdbtzGDn4VYs65O7J2kzg4tXoVJE1joCjS2P0BugXMHVGriSWOyhmtvQgW6EP0CfskBWek9Tq2+3Mn",
	"zQ/58eNHcj4Z6/vBM3EMpvpkhMLgOVD6OedIwthdkGxJvhLxosvWcySO+onD0DmL0XleDOLXHfX/+xg8",
	"616wLfWoX/8Vakxl/rO487XIu2HxPt8y+/2+MDUFK25Qc6YyrxhGbpHrjmpo0HWjUAlXNUV03RX0Y4gQ",
	"Iu5gQ0ziLPzx2++6YK8hCloKBVx89w00gptefQJyDW6KCVofImNPAdbUed6AY+j8JhTAPuoPwkwGrH29",
	"g9hiBCG0LQW4aT1tSaDHmiC2BEK/jhRiuWKjkUzhafRzhNWnz+L78PY1nJ2+/D9MJ+BNiiyUkAivAQNc",
	"PcXwVbniFV/F3UBX4ELC0KNtHdOJENa47ghcTRxd3IFv0oGJxEyEBoERcMW2c8QRQuvHroa1INsWPCc+",
	"311evldS4xgAO8+UnHkP1qMEKiA4tgSeacWnyzOwyNATMgTlBzuoXdOQqP3YOt6EEq6ii11G3XiBduyR",
	"c3J63MGaVix046WmGm5cbP0YNSXOqjMPGWzI6ddU9RgzXJfYL8wgfiCJLos4y+Uh++/U7R1VdDt0yIln",
	"CANZ1zgL0SvoAN7aUYTYUmkKQ7fYDx2Zynzr4cbLtSJUpOBqWD5798VPZVkC3boQc4TJxhhI9LZmzFQm",
	"RHG8MfvCOA4R2dJDiN9/OJ9S2Owcb7KdA7inQC0mSGExYzGFabz0GE1lRnEnQikjlh6Dk3P9CF9HQrC+",
	"pgKEBsJINbQklALV+kmJnJOUaqbzgTQ5xyhPl6dHoBzHF89NYXq8df3Ym+rl2Vlhesf579lyeQDqONKG",
	"RJEmGT0EetF6idDeT28Y+x5lV8Ibn0RzJ3Il9T6BP04p1XONH7l+jKa8oL4bHDsNAtd+jNW6Q742n7ey",
	"i5hQPEwowVTUoAZLuBTCCC5q7SPPhx1JbksInePrL/UAE9VpTSj4bktZ+3dRtDEOoVosSMRLKKeN0vp+",
	"FsgJ+3gyB/hPBbIvjLY6J1Sb6ue8O6fiIJ5fDtf8+iPZqIT9QBJcngz3C3R7t/EZadQjR2dhOjF3MRmZ",
	"lb316Lr6XszLclku/xbz7PAhyn0qx8Y/xPIKdOoJ2jhVNOVJ0uicgQ53JCWcR8i31hR0BHEYVIqeu532",
	"0hVrS9yBjB1BUsvUgWGLnasPrcSFIhVR629g67uxTz1XZ+cYqS5W3LktBXCcYNS+R8cZwtzYpx5BOu6g",
	"LBcNYRyFwiINjYvRWgrhMN4CoBCEFgeqYb07tqr2cgOHgQQ0balFlit+m2dJ0IuSBkA2kfjJgR6OV/Dk",
	"rFvx60OvIM6qVltJtjBgbLPydU0hENeDdzy1+qkFmLcusoZ0KWivSeDV+3NT3ClrEsa+MH4gxsGZyrwo",
	"l+ULnRYY26TDxZEQN5SeN4cAzmtTma8pziIu7j+Uni+Xf/Ew+ncPotnFIw+iyyPxz2D3hXm5XD5l9IBy",
	"8dhbTj1MjVGfI5TUqtmfC+642gLJ1lmCGwyp8iI04tO7bf/nAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
